#!/bin/bash
if [ "$UID" != "0" ];then
  echo "You Must Run Be A Root User"
  exit 0
fi
if [ "$1" = "start" ];then
  service mysqld start
  service apache2 start
fi
if [ "$1" = "stop" ];then
  service mysqld stop
  service apache2 stop
fi
if [ "$1" = "stop" ];then
  service mysqld  restart 
  service apache2 restart 
fi

